name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
    paths:
      - 'barcode_label_app/**'
      - '.github/workflows/build-exe.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'barcode_label_app/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd barcode_label_app
        pip install -r requirements.txt
    
    - name: Build executable
      run: |
        cd barcode_label_app
        pyinstaller --onefile --windowed --name=BarcodeGenerator --add-data="logo.png;." --add-data="data;data" --hidden-import=tkinter --hidden-import=tkinter.ttk --hidden-import=tkinter.filedialog --hidden-import=tkinter.messagebox --hidden-import=PIL._tkinter_finder --hidden-import=reportlab.graphics.barcode.code128 --hidden-import=reportlab.graphics.barcode.code93 --hidden-import=reportlab.graphics.barcode.code39 --hidden-import=reportlab.graphics.barcode.common --hidden-import=reportlab.graphics.barcode.widgets --hidden-import=reportlab.graphics.barcode.eanbc --hidden-import=reportlab.graphics.barcode.ecc200datamatrix --hidden-import=reportlab.graphics.barcode.fourstate --hidden-import=reportlab.graphics.barcode.lto --hidden-import=reportlab.graphics.barcode.qr --hidden-import=reportlab.graphics.barcode.usps --hidden-import=reportlab.graphics.barcode.usps4s --collect-all=treepoem --collect-all=PIL --collect-all=pandas --collect-all=reportlab simple_barcode_app.py
    
    - name: Create distribution package
      run: |
        cd barcode_label_app
        mkdir BarcodeGenerator_Distribution
        copy dist\BarcodeGenerator.exe BarcodeGenerator_Distribution\
        copy logo.png BarcodeGenerator_Distribution\
        xcopy /E /I data BarcodeGenerator_Distribution\data
      shell: cmd
    
    - name: Create README file
      run: |
        cd barcode_label_app
        $readme = @"
        # Barcode Label Generator
        
        ## Quick Start
        1. Double-click BarcodeGenerator.exe to start
        2. Select your Excel file or use the default one
        3. Browse to change the logo if needed  
        4. Enter a serial number to lookup and generate labels
        
        No Python installation required!
        
        Generated with PyInstaller on $(Get-Date)
        "@
        $readme | Out-File -FilePath "BarcodeGenerator_Distribution\README.txt" -Encoding UTF8
      shell: powershell
    
    - name: Upload complete distribution
      uses: actions/upload-artifact@v4
      with:
        name: BarcodeGenerator-Windows-Complete
        path: barcode_label_app/BarcodeGenerator_Distribution/
        retention-days: 30
    
    - name: Upload executable only
      uses: actions/upload-artifact@v4
      with:
        name: BarcodeGenerator-exe
        path: barcode_label_app/dist/BarcodeGenerator.exe
        retention-days: 30
    
    - name: Show build info
      run: |
        cd barcode_label_app
        Write-Host "Build completed successfully!"
        Write-Host "Executable size:"
        Get-ChildItem dist\BarcodeGenerator.exe | Format-Table Name, Length
        Write-Host "Distribution contents:"
        Get-ChildItem BarcodeGenerator_Distribution | Format-Table Name, Length
      shell: powershell
